baseURL = 'https://oracle-samples.github.io/ml4code'
languageCode = 'en-us'
title = 'ml4code'
enableGitInfo = true

[params]
  BookFavicon = "favicon.ico"
  BookLogo = "logo.png"
  math = true
  BookComments = false

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]